# Generated by Django 4.2 on 2024-02-28 17:15

import api.source_json
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResearchDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.URLField()),
                ('source_name', models.CharField(max_length=30)),
                ('file_content', models.FileField(blank=True, null=True, storage=api.source_json.OverWriteStorage(), upload_to=api.source_json.get_file_path)),
                ('file_name', models.CharField(max_length=500)),
                ('file_size', models.BigIntegerField(default=0)),
                ('file_type', models.CharField(max_length=20)),
                ('received_on', models.DateTimeField(auto_now_add=True)),
                ('processed_on', models.DateTimeField(null=True)),
                ('status', models.CharField(max_length=12)),
                ('bureau_code', models.CharField(max_length=20)),
            ],
        ),
    ]
