# Generated by Django 4.2 on 2024-02-28 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ResearchDocument',
            new_name='SyncFromSource',
        ),
    ]
